# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c6e424e4a98793c0680424d7d146806b"
application_url = "https://ovalle-ftp-sync-r6x88e9uj-iulians-projects-3e3f2a9b.vercel.app"
embedded = true
name = "ovalle-ftp-sync"
handle = "ftp-order-sync-ovalle"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"
  
  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/order/created"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_orders,read_inventory"

[auth]
redirect_urls = [ "https://ovalle-ftp-sync-r6x88e9uj-iulians-projects-3e3f2a9b.vercel.app/auth/callback" ]

[pos]
embedded = false
